# Use the official PostgreSQL image
FROM postgres:15

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=w40k_deal_finder

# Expose the PostgreSQL default port
EXPOSE 5432