export const factions = [
  'Adepta Sororitas',
  'Adeptus Custodes',
  'Adeptus Mechanicus',
  'Aeldari',
  'Astra Militarum',
  'Black Templars',
  'Blood Angels',
  'Chaos Daemons',
  'Chaos Knights',
  'Chaos Space Marines',
  'Dark Angels',
  'Death Guard',
  'Deathwatch',
  'Drukhari',
  'Genestealer Cults',
  'Grey Knights',
  'Harlequins',
  'Imperial Knights',
  'Imperial Guard',
  'Inquisition',
  'Leagues of Votann',
  'Necrons',
  'Orks',
  'Raven Guard',
  'Salamanders',
  'Space Marines',
  'Space Wolves',
  'Tau Empire',
  'Thousand Sons',
  'Tyranids',
  'Ultramarines',
  'White Scars',
  'World Eaters',
  'Ynnari',
];