export const factions = [
  { name: 'Adepta Sororitas' },
  { name: 'Adeptus Custodes' },
  { name: 'Adeptus Mechanicus' },
  { name: 'Aeldari' },
  { name: 'Astra Militarum' },
  { name: 'Black Templars' },
  { name: 'Blood Angels' },
  { name: 'Chaos Daemons' },
  { name: 'Chaos Knights' },
  { name: 'Chaos Space Marines' },
  { name: 'Dark Angels' },
  { name: 'Death Guard' },
  { name: 'Deathwatch' },
  { name: 'Drukhari' },
  { name: 'Genestealer Cults' },
  { name: 'Grey Knights' },
  { name: 'Harlequins' },
  { name: 'Imperial Knights' },
  { name: 'Imperial Guard' },
  { name: 'Inquisition' },
  { name: 'Leagues of Votann' },
  { name: 'Necrons' },
  { name: 'Orks' },
  { name: 'Raven Guard' },
  { name: 'Salamanders' },
  { name: 'Space Marines' },
  { name: 'Space Wolves' },
  { name: 'Tau Empire' },
  { name: 'Thousand Sons' },
  { name: 'Tyranids' },
  { name: 'Ultramarines' },
  { name: 'White Scars' },
  { name: 'World Eaters' },
  { name: 'Ynnari' },
];